# Final figure and table organisation

source("R/00_utils_io.R")

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(tibble)
  library(readr)
  library(ggplot2)
})

if (!exists("ensure_dir")) {
  ensure_dir <- function(path) {
    dir.create(path, recursive = TRUE, showWarnings = FALSE)
  }
}

if (!exists("message_header")) {
  message_header <- function(x) {
    message("\n", paste(rep("=", 80), collapse = ""))
    message(x)
    message(paste(rep("=", 80), collapse = ""))
  }
}

ensure_project_dirs()
ensure_dir("results/final_figures")
ensure_dir("results/final_tables")
ensure_dir("results/tables")
ensure_dir("docs")

final_fig_dir <- "results/final_figures"
final_tab_dir <- "results/final_tables"

message_header("Available figures before final organisation")

available_figures <- list.files(
  "results/figures",
  pattern = "\\.png$",
  recursive = TRUE,
  full.names = TRUE
)

print(available_figures)

message_header("Create Figure 1: study workflow")

workflow_steps <- tibble(
  step = 1:7,
  label = c(
    "Public IBDMDB/HMP2\nmulti-omics data",
    "Metadata, microbiome,\nmetabolome matching",
    "QC, filtering,\nCLR/log transformation",
    "Single-omics\nassociation analysis",
    "Taxa-metabolite\ncorrelation",
    "mixOmics/sPLS\nfeature selection",
    "Multi-evidence\ncandidate ranking"
  ),
  x = step,
  y = 1
)

p_workflow <- ggplot(workflow_steps, aes(x = x, y = y)) +
  geom_label(
    aes(label = label),
    size = 3.5,
    label.size = 0.35,
    label.padding = unit(0.35, "lines")
  ) +
  geom_segment(
    data = workflow_steps %>% filter(step < max(step)),
    aes(x = x + 0.39, xend = x + 0.61, y = y, yend = y),
    arrow = arrow(length = unit(0.15, "inches")),
    linewidth = 0.4
  ) +
  scale_x_continuous(limits = c(0.4, 7.6)) +
  labs(
    title = "Study workflow for microbiome-metabolome biomarker discovery",
    x = NULL,
    y = NULL
  ) +
  theme_void(base_size = 12) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

ggsave(
  file.path(final_fig_dir, "figure_01_study_workflow.png"),
  p_workflow,
  width = 12,
  height = 3.2,
  dpi = 300
)

message_header("Copy selected main figures")

first_existing <- function(paths) {
  hit <- paths[file.exists(paths)]
  if (length(hit) == 0) {
    return(NA_character_)
  }
  hit[1]
}

copy_final_figure <- function(figure_number, title, output_name, candidates) {
  source_path <- first_existing(candidates)
  output_path <- file.path(final_fig_dir, output_name)
  
  if (!is.na(source_path)) {
    file.copy(source_path, output_path, overwrite = TRUE)
    status <- "copied"
  } else {
    status <- "missing"
  }
  
  tibble(
    figure_number = figure_number,
    figure_title = title,
    source_path = source_path,
    final_path = output_path,
    status = status
  )
}

figure_manifest <- bind_rows(
  tibble(
    figure_number = 1,
    figure_title = "Study workflow",
    source_path = "generated by R/12_make_figures_tables.R",
    final_path = file.path(final_fig_dir, "figure_01_study_workflow.png"),
    status = if_else(
      file.exists(file.path(final_fig_dir, "figure_01_study_workflow.png")),
      "generated",
      "missing"
    )
  ),
  
  copy_final_figure(
    2,
    "Sample matching flow",
    "figure_02_sample_matching_flow.png",
    c(
      "results/figures/sample_matching_flow.png",
      "results/figures/sample_retention_flow.png",
      "results/figures/cohort_matching_flow.png"
    )
  ),
  
  copy_final_figure(
    3,
    "Diagnosis group distribution after matching",
    "figure_03_group_distribution.png",
    c(
      "results/figures/group_distribution_barplot.png",
      "results/figures/diagnosis_group_distribution.png",
      "results/figures/group_distribution.png"
    )
  ),
  
  copy_final_figure(
    4,
    "Microbiome alpha diversity by diagnosis",
    "figure_04_microbiome_alpha_diversity.png",
    c(
      "results/figures/shannon_diversity_by_diagnosis.png",
      "results/figures/alpha_diversity_by_diagnosis.png",
      "results/figures/alpha_diversity_boxplot.png"
    )
  ),
  
  copy_final_figure(
    5,
    "Microbiome beta diversity ordination",
    "figure_05_microbiome_beta_diversity_ordination.png",
    c(
      "results/figures/bray_curtis_pcoa_by_diagnosis.png",
      "results/figures/aitchison_pca_by_diagnosis.png",
      "results/figures/aitchison_pcoa_by_diagnosis.png",
      "results/figures/beta_diversity_ordination.png"
    )
  ),
  
  copy_final_figure(
    6,
    "Metabolomics PCA by diagnosis",
    "figure_06_metabolomics_pca.png",
    c(
      "results/figures/metabolomics_pca_by_diagnosis.png",
      "results/figures/metabolomics_pca_qc_by_diagnosis.png",
      "results/figures/metabolomics_pca.png"
    )
  ),
  
  copy_final_figure(
    7,
    "Genus-level taxa differential abundance",
    "figure_07_taxa_differential_abundance.png",
    c(
      "results/figures/taxa_differential_abundance_dotplot.png",
      "results/figures/taxa_effect_size_volcano.png",
      "results/figures/genus_level_taxa_differential_abundance.png"
    )
  ),
  
  copy_final_figure(
    8,
    "Disease-associated metabolite features",
    "figure_08_metabolite_association_volcano.png",
    c(
      "results/figures/metabolite_volcano.png",
      "results/figures/metabolite_association_volcano.png",
      "results/figures/metabolite_association_models.png"
    )
  ),
  
  copy_final_figure(
    9,
    "Top disease-associated metabolite heatmap",
    "figure_09_top_metabolite_heatmap.png",
    c(
      "results/figures/top_metabolites_heatmap.png",
      "results/figures/metabolite_heatmap.png"
    )
  ),
  
  copy_final_figure(
    10,
    "Taxa-metabolite correlation heatmap",
    "figure_10_taxa_metabolite_correlation_heatmap.png",
    c(
      "results/figures/taxa_metabolite_correlation_heatmap.png",
      "results/figures/covariate_adjusted_correlation_heatmap.png"
    )
  ),
  
  copy_final_figure(
    11,
    "mixOmics selected feature loading plot",
    "figure_11_mixomics_loading_plot.png",
    c(
      "results/figures/mixomics_microbiome_loading_plot.png",
      "results/figures/mixomics_metabolite_loading_plot.png",
      "results/figures/mixomics_individuals_plot.png"
    )
  ),
  
  copy_final_figure(
    12,
    "Final candidate biomarker ranking",
    "figure_12_final_candidate_biomarker_ranking.png",
    c(
      "results/figures/top_candidate_biomarker_dotplot.png",
      "results/figures/top_candidate_biomarker_heatmap.png",
      "results/figures/final_candidate_biomarker_ranking.png"
    )
  )
)

figure_manifest <- figure_manifest %>%
  mutate(
    final_exists = file.exists(final_path),
    file_size_bytes = if_else(
      final_exists,
      as.numeric(file.info(final_path)$size),
      NA_real_
    )
  )

write_tsv(
  figure_manifest,
  "results/tables/final_figure_manifest.tsv"
)

message("Final figure manifest:")
print(figure_manifest, n = Inf, width = Inf)

message_header("Create final report tables")

read_tsv_if_exists <- function(path) {
  if (file.exists(path)) {
    readr::read_tsv(path, show_col_types = FALSE)
  } else {
    tibble()
  }
}

sample_flow <- read_tsv_if_exists("results/tables/sample_matching_flow.tsv")
group_distribution <- read_tsv_if_exists("results/tables/group_distribution.tsv")
taxa_filtering <- read_tsv_if_exists("results/tables/taxa_filtering_summary.tsv")
metab_filtering <- read_tsv_if_exists("results/tables/metabolite_filtering_summary.tsv")
alpha_results <- read_tsv_if_exists("results/tables/alpha_diversity_results.tsv")
permanova_results <- read_tsv_if_exists("results/tables/permanova_results.tsv")
betadisper_results <- read_tsv_if_exists("results/tables/betadisper_results.tsv")
taxa_all <- read_tsv_if_exists("results/tables/maaslin2_taxa_all_results.tsv")
taxa_sig <- read_tsv_if_exists("results/tables/maaslin2_taxa_significant_results.tsv")
metab_all <- read_tsv_if_exists("results/tables/metabolite_association_all_results.tsv")
metab_sig <- read_tsv_if_exists("results/tables/metabolite_association_significant_results.tsv")
integration_summary <- read_tsv_if_exists("results/tables/integration_feature_selection_summary.tsv")
spearman_sig <- read_tsv_if_exists("results/tables/taxa_metabolite_spearman_significant_pairs.tsv")
mixomics_perf <- read_tsv_if_exists("results/tables/mixomics_model_performance.tsv")
ranking <- read_tsv_if_exists("results/tables/final_candidate_biomarker_ranking.tsv")
ranking_annotated <- read_tsv_if_exists("results/tables/final_candidate_biomarker_ranking_annotated.tsv")
annotation_coverage <- read_tsv_if_exists("results/tables/metabolite_annotation_coverage_summary.tsv")

key_numbers <- tibble(
  metric = c(
    "metadata_samples_total",
    "matched_multiomics_samples",
    "primary_independent_samples",
    "genus_level_taxa_tested",
    "metabolite_features_tested",
    "taxa_maaslin2_results",
    "taxa_fdr_significant_results",
    "metabolite_maaslin2_results",
    "metabolite_fdr_significant_results",
    "selected_taxa_for_integration",
    "selected_metabolites_for_integration",
    "significant_taxa_metabolite_pairs",
    "mixomics_apparent_accuracy",
    "final_candidate_pairs_ranked"
  ),
  value = c(
    if_else(nrow(sample_flow) > 0 && "n_samples" %in% names(sample_flow),
            as.character(sample_flow$n_samples[1]),
            NA_character_),
    if_else(nrow(sample_flow) > 0 && "step" %in% names(sample_flow) && "n_samples" %in% names(sample_flow),
            as.character(sample_flow$n_samples[which.max(seq_len(nrow(sample_flow)))]),
            NA_character_),
    if_else(nrow(group_distribution) > 0 && "analysis_set" %in% names(group_distribution),
            as.character(sum(group_distribution$n_samples[group_distribution$analysis_set == "primary_independent_set"], na.rm = TRUE)),
            NA_character_),
    as.character(nrow(taxa_all) / 4),
    as.character(nrow(metab_all) / 4),
    as.character(nrow(taxa_all)),
    as.character(nrow(taxa_sig)),
    as.character(nrow(metab_all)),
    as.character(nrow(metab_sig)),
    if_else(nrow(integration_summary) > 0,
            as.character(integration_summary$n_after_filtering[integration_summary$feature_type == "microbiome_taxa"][1]),
            NA_character_),
    if_else(nrow(integration_summary) > 0,
            as.character(integration_summary$n_after_filtering[integration_summary$feature_type == "metabolites"][1]),
            NA_character_),
    as.character(nrow(spearman_sig)),
    if_else(nrow(mixomics_perf) > 0 && "apparent_accuracy" %in% names(mixomics_perf),
            as.character(round(mixomics_perf$apparent_accuracy[1], 3)),
            NA_character_),
    as.character(nrow(ranking))
  )
)

write_tsv(
  key_numbers,
  file.path(final_tab_dir, "table_01_key_project_numbers.tsv")
)

if (nrow(group_distribution) > 0) {
  write_tsv(
    group_distribution,
    file.path(final_tab_dir, "table_02_group_distribution.tsv")
  )
}

single_omics_summary <- tibble(
  analysis = c(
    "Alpha diversity",
    "PERMANOVA",
    "Beta dispersion",
    "MaAsLin2 genus-level taxa",
    "MaAsLin2 metabolite features"
  ),
  result_summary = c(
    if_else(nrow(alpha_results) > 0,
            paste0(nrow(alpha_results), " alpha-diversity tests available"),
            "not available"),
    if_else(nrow(permanova_results) > 0,
            paste0(nrow(permanova_results), " PERMANOVA rows available"),
            "not available"),
    if_else(nrow(betadisper_results) > 0,
            paste0(nrow(betadisper_results), " beta-dispersion rows available"),
            "not available"),
    paste0(nrow(taxa_all), " results; ", nrow(taxa_sig), " FDR-significant results"),
    paste0(nrow(metab_all), " results; ", nrow(metab_sig), " FDR-significant results")
  ),
  interpretation = c(
    "Used to evaluate within-sample microbiome diversity by diagnosis.",
    "Used to test community-level microbiome composition differences by diagnosis.",
    "Used to check whether PERMANOVA signal may be influenced by group dispersion.",
    "No genus-level taxa survived FDR correction; taxa were retained as exploratory signals.",
    "Metabolomics showed disease-associated feature-level signal."
  )
)

write_tsv(
  single_omics_summary,
  file.path(final_tab_dir, "table_03_single_omics_summary.tsv")
)

if (nrow(integration_summary) > 0) {
  write_tsv(
    integration_summary,
    file.path(final_tab_dir, "table_04_integration_feature_selection.tsv")
  )
}

if (nrow(spearman_sig) > 0) {
  spearman_top <- spearman_sig %>%
    arrange(correlation_fdr, desc(abs(spearman_rho))) %>%
    select(
      taxon,
      taxon_label,
      metabolite,
      metabolite_label,
      spearman_rho,
      correlation_fdr,
      n_samples,
      everything()
    ) %>%
    slice_head(n = 30)
  
  write_tsv(
    spearman_top,
    file.path(final_tab_dir, "table_05_top_taxa_metabolite_correlations.tsv")
  )
}

if (nrow(mixomics_perf) > 0) {
  write_tsv(
    mixomics_perf,
    file.path(final_tab_dir, "table_06_mixomics_model_summary.tsv")
  )
}

ranking_for_table <- if (nrow(ranking_annotated) > 0) {
  ranking_annotated
} else {
  ranking
}

if (nrow(ranking_for_table) > 0) {
  top_ranking_table <- ranking_for_table %>%
    slice_head(n = 30) %>%
    select(
      rank,
      taxon_label,
      metabolite,
      any_of(c("metabolite_display_name", "annotation_status")),
      metabolite_fdr,
      spearman_rho,
      correlation_fdr,
      spls_loading,
      overall_score,
      biological_note,
      everything()
    )
  
  write_tsv(
    top_ranking_table,
    file.path(final_tab_dir, "table_07_top_candidate_biomarker_pairs.tsv")
  )
}

if (nrow(annotation_coverage) > 0) {
  write_tsv(
    annotation_coverage,
    file.path(final_tab_dir, "table_08_metabolite_annotation_coverage.tsv")
  )
}

message_header("Copy selected original tables into final_tables")

copy_table <- function(source_path, output_name, expected_empty = FALSE) {
  output_path <- file.path(final_tab_dir, output_name)
  
  if (file.exists(source_path)) {
    file.copy(source_path, output_path, overwrite = TRUE)
    dat <- read_tsv_if_exists(source_path)
    status <- if_else(nrow(dat) == 0 && !expected_empty, "exists_but_empty", "copied")
    n_rows <- nrow(dat)
    n_cols <- ncol(dat)
  } else {
    status <- "missing"
    n_rows <- NA_integer_
    n_cols <- NA_integer_
  }
  
  tibble(
    source_path = source_path,
    final_path = output_path,
    status = status,
    n_rows = n_rows,
    n_cols = n_cols,
    expected_empty = expected_empty
  )
}

table_manifest <- bind_rows(
  copy_table("results/tables/sample_matching_flow.tsv", "source_sample_matching_flow.tsv"),
  copy_table("results/tables/group_distribution.tsv", "source_group_distribution.tsv"),
  copy_table("results/tables/alpha_diversity_results.tsv", "source_alpha_diversity_results.tsv"),
  copy_table("results/tables/permanova_results.tsv", "source_permanova_results.tsv"),
  copy_table("results/tables/betadisper_results.tsv", "source_betadisper_results.tsv"),
  copy_table("results/tables/maaslin2_taxa_all_results.tsv", "source_maaslin2_taxa_all_results.tsv"),
  copy_table("results/tables/maaslin2_taxa_significant_results.tsv", "source_maaslin2_taxa_significant_results.tsv", expected_empty = TRUE),
  copy_table("results/tables/metabolite_association_significant_results.tsv", "source_metabolite_association_significant_results.tsv"),
  copy_table("results/tables/integration_feature_selection_summary.tsv", "source_integration_feature_selection_summary.tsv"),
  copy_table("results/tables/taxa_metabolite_spearman_significant_pairs.tsv", "source_taxa_metabolite_spearman_significant_pairs.tsv"),
  copy_table("results/tables/covariate_adjusted_correlation_pairs.tsv", "source_covariate_adjusted_correlation_pairs.tsv"),
  copy_table("results/tables/mixomics_selected_microbiome_features.tsv", "source_mixomics_selected_microbiome_features.tsv"),
  copy_table("results/tables/mixomics_selected_metabolite_features.tsv", "source_mixomics_selected_metabolite_features.tsv"),
  copy_table("results/tables/mixomics_model_performance.tsv", "source_mixomics_model_performance.tsv"),
  copy_table("results/tables/final_candidate_biomarker_ranking.tsv", "source_final_candidate_biomarker_ranking.tsv"),
  copy_table("results/tables/final_candidate_biomarker_ranking_annotated.tsv", "source_final_candidate_biomarker_ranking_annotated.tsv")
)

write_tsv(
  table_manifest,
  "results/tables/final_table_manifest.tsv"
)

message("Final table manifest:")
print(table_manifest, n = Inf, width = Inf)

message_header("Final output QC")

figure_qc <- figure_manifest %>%
  transmute(
    output_type = "figure",
    item = figure_title,
    path = final_path,
    status = case_when(
      status == "missing" ~ "missing",
      final_exists & !is.na(file_size_bytes) & file_size_bytes > 0 ~ "ok",
      TRUE ~ "problem"
    ),
    detail = paste0("figure_number=", figure_number, "; source=", source_path)
  )

table_qc <- table_manifest %>%
  transmute(
    output_type = "table",
    item = basename(final_path),
    path = final_path,
    status = case_when(
      status == "missing" ~ "missing",
      status == "exists_but_empty" ~ "empty_unexpected",
      status == "copied" ~ "ok",
      TRUE ~ status
    ),
    detail = paste0("n_rows=", n_rows, "; n_cols=", n_cols, "; expected_empty=", expected_empty)
  )

final_output_qc <- bind_rows(figure_qc, table_qc)

write_tsv(
  final_output_qc,
  "results/tables/final_output_qc.tsv"
)

print(final_output_qc, n = Inf, width = Inf)

message_header("Write markdown manifest for report writing")

manifest_lines <- c(
  "# Figure and table manifest",
  "",
  "## Main figures",
  "",
  paste0(
    "- Figure ", figure_manifest$figure_number, ". ",
    figure_manifest$figure_title,
    " — `", figure_manifest$final_path, "`",
    " [", figure_manifest$status, "]"
  ),
  "",
  "## Final tables",
  "",
  paste0(
    "- `", table_manifest$final_path, "`",
    " [", table_manifest$status,
    "; rows=", table_manifest$n_rows,
    "; cols=", table_manifest$n_cols,
    "]"
  ),
  "",
  "## Key numbers",
  "",
  paste0("- ", key_numbers$metric, ": ", key_numbers$value)
)

writeLines(
  manifest_lines,
  "docs/figure_table_manifest.md"
)

message_header("Final organisation completed")

message("Main figures written to: results/final_figures/")
message("Final tables written to: results/final_tables/")
message("QC files written:")
message("- results/tables/final_figure_manifest.tsv")
message("- results/tables/final_table_manifest.tsv")
message("- results/tables/final_output_qc.tsv")
message("- docs/figure_table_manifest.md")